language: clojure

lein: lein2

script: lein2 build

jdk:
  - oraclejdk8

after_success:
  - CLOVERAGE_VERSION=1.0.8 lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
