#%RAML 0.8
title: GitHub API
version: v3
baseUri: https://api.github.com
/user:
/users:
  /{userId}:
    uriParameters:
      userId:
        type: integer
    get:
      response:
         200:
           body:
             application/text:
               "bla"

    /followers:
    /following:
    /keys:
      /{keyId}:
        uriParameters:
          keyId:
            type: integer
        get:
          response:
            200:
              body:
                application/text:
                  "bla"
